import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Test</h1>
      </main>
    </>
  );
}

// Page Config
// Home.disabledLayout = true;

export async function getServerSideProps(context) {
  const endpoints = [];

  // Return our response in the allData variable as an array
  const data = await Promise.all(
    endpoints.map((endpoint) => http.get(endpoint))
  ).then(([]) => ({}));

  return {
    props: {
      title: "Home",
      url: context?.resolvedUrl,
      data,
    }, // will be passed to the page component as props
  };
}
